//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THD.Core.Api.Repository.ReportFiles {
    
    public partial class rptR7 : DevExpress.XtraReports.UI.XtraReport {
        private void InitializeComponent() {
            DevExpress.XtraReports.ReportInitializer reportInitializer = new DevExpress.XtraReports.ReportInitializer(this, "THD.Core.Api.Repository.ReportFiles.rptR7.repx");

            // Controls
            this.TopMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.TopMarginBand>("TopMargin");
            this.BottomMargin = reportInitializer.GetControl<DevExpress.XtraReports.UI.BottomMarginBand>("BottomMargin");
            this.Detail = reportInitializer.GetControl<DevExpress.XtraReports.UI.DetailBand>("Detail");
            this.ReportHeader = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportHeaderBand>("ReportHeader");
            this.ReportFooter = reportInitializer.GetControl<DevExpress.XtraReports.UI.ReportFooterBand>("ReportFooter");
            this.richText2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText2");
            this.checkBox2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox2");
            this.checkBox3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox3");
            this.checkBox4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox4");
            this.checkBox5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox5");
            this.label6 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label6");
            this.richText1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRRichText>("richText1");
            this.checkBox1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRCheckBox>("checkBox1");
            this.label30 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label30");
            this.label29 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label29");
            this.label27 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label27");
            this.label26 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label26");
            this.label46 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label46");
            this.pictureBox2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRPictureBox>("pictureBox2");
            this.label48 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label48");
            this.label47 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label47");
            this.label49 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label49");
            this.label50 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label50");
            this.label51 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label51");
            this.label52 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label52");
            this.label53 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label53");
            this.label54 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label54");
            this.label55 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label55");
            this.label57 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label57");
            this.label58 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label58");
            this.label59 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label59");
            this.label60 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label60");
            this.label61 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label61");
            this.label62 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label62");
            this.label63 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label63");
            this.label56 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label56");
            this.label1 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label1");
            this.label2 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label2");
            this.label3 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label3");
            this.label4 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label4");
            this.label5 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label5");
            this.label31 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label31");
            this.label41 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label41");
            this.label39 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label39");
            this.label40 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label40");
            this.label44 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label44");
            this.label64 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label64");
            this.label65 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label65");
            this.label66 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label66");
            this.label67 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label67");
            this.label68 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label68");
            this.label69 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label69");
            this.label70 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label70");
            this.label71 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label71");
            this.label72 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label72");
            this.label73 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label73");
            this.label74 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label74");
            this.label75 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label75");
            this.label76 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label76");
            this.label77 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label77");
            this.label78 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label78");
            this.label79 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label79");
            this.label80 = reportInitializer.GetControl<DevExpress.XtraReports.UI.XRLabel>("label80");

            // Data Sources
            this.objectDataSource1 = reportInitializer.GetDataSource<DevExpress.DataAccess.ObjectBinding.ObjectDataSource>("objectDataSource1");
        }
        private DevExpress.XtraReports.UI.TopMarginBand TopMargin;
        private DevExpress.XtraReports.UI.BottomMarginBand BottomMargin;
        private DevExpress.XtraReports.UI.DetailBand Detail;
        private DevExpress.XtraReports.UI.ReportHeaderBand ReportHeader;
        private DevExpress.XtraReports.UI.ReportFooterBand ReportFooter;
        private DevExpress.XtraReports.UI.XRRichText richText2;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox2;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox3;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox4;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox5;
        private DevExpress.XtraReports.UI.XRLabel label6;
        private DevExpress.XtraReports.UI.XRRichText richText1;
        private DevExpress.XtraReports.UI.XRCheckBox checkBox1;
        private DevExpress.XtraReports.UI.XRLabel label30;
        private DevExpress.XtraReports.UI.XRLabel label29;
        private DevExpress.XtraReports.UI.XRLabel label27;
        private DevExpress.XtraReports.UI.XRLabel label26;
        private DevExpress.XtraReports.UI.XRLabel label46;
        private DevExpress.XtraReports.UI.XRPictureBox pictureBox2;
        private DevExpress.XtraReports.UI.XRLabel label48;
        private DevExpress.XtraReports.UI.XRLabel label47;
        private DevExpress.XtraReports.UI.XRLabel label49;
        private DevExpress.XtraReports.UI.XRLabel label50;
        private DevExpress.XtraReports.UI.XRLabel label51;
        private DevExpress.XtraReports.UI.XRLabel label52;
        private DevExpress.XtraReports.UI.XRLabel label53;
        private DevExpress.XtraReports.UI.XRLabel label54;
        private DevExpress.XtraReports.UI.XRLabel label55;
        private DevExpress.XtraReports.UI.XRLabel label57;
        private DevExpress.XtraReports.UI.XRLabel label58;
        private DevExpress.XtraReports.UI.XRLabel label59;
        private DevExpress.XtraReports.UI.XRLabel label60;
        private DevExpress.XtraReports.UI.XRLabel label61;
        private DevExpress.XtraReports.UI.XRLabel label62;
        private DevExpress.XtraReports.UI.XRLabel label63;
        private DevExpress.XtraReports.UI.XRLabel label56;
        private DevExpress.XtraReports.UI.XRLabel label1;
        private DevExpress.XtraReports.UI.XRLabel label2;
        private DevExpress.XtraReports.UI.XRLabel label3;
        private DevExpress.XtraReports.UI.XRLabel label4;
        private DevExpress.XtraReports.UI.XRLabel label5;
        private DevExpress.XtraReports.UI.XRLabel label31;
        private DevExpress.XtraReports.UI.XRLabel label41;
        private DevExpress.XtraReports.UI.XRLabel label39;
        private DevExpress.XtraReports.UI.XRLabel label40;
        private DevExpress.XtraReports.UI.XRLabel label44;
        private DevExpress.XtraReports.UI.XRLabel label64;
        private DevExpress.XtraReports.UI.XRLabel label65;
        private DevExpress.XtraReports.UI.XRLabel label66;
        private DevExpress.XtraReports.UI.XRLabel label67;
        private DevExpress.XtraReports.UI.XRLabel label68;
        private DevExpress.XtraReports.UI.XRLabel label69;
        private DevExpress.XtraReports.UI.XRLabel label70;
        private DevExpress.XtraReports.UI.XRLabel label71;
        private DevExpress.XtraReports.UI.XRLabel label72;
        private DevExpress.XtraReports.UI.XRLabel label73;
        private DevExpress.XtraReports.UI.XRLabel label74;
        private DevExpress.XtraReports.UI.XRLabel label75;
        private DevExpress.XtraReports.UI.XRLabel label76;
        private DevExpress.XtraReports.UI.XRLabel label77;
        private DevExpress.XtraReports.UI.XRLabel label78;
        private DevExpress.XtraReports.UI.XRLabel label79;
        private DevExpress.XtraReports.UI.XRLabel label80;
        private DevExpress.DataAccess.ObjectBinding.ObjectDataSource objectDataSource1;
    }
}
